name: navigation
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^5.0.4

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain
  main_page:
    path: ../features/home
  cart:
    path: ../features/cart
  order_history:
    path: ../features/order_history
  settings:
    path: ../features/settings
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner:

flutter:


