class AppString {
  static const String byn = ' BYN';
  static const String donut = 'Donut';
  static const String youHaveAdded = 'You have added \'';
  static const String toTheCart = '\' to the cart!';
  static const String add = 'Add';
  static const String cartTotalCost = 'Total cost:';
  static const String makeAnOrder = 'Make an order';
  static const String emptyCartScreen =
      'Your shopping cart is empty. You can select dishes on the home screen.';
  static const String cost = 'Cost: ';
  static const String ingredients = 'Ingredients';
  static const String appBarTitle = 'Delicious and ellipsis...';
  static const String signInTitle = 'Delicious and ellipsis ';
  static const String signIn = 'Sign In';
  static const String orSignInUsingGoogle = 'Or Sign In using Google';
  static const String errorMessage = 'An error occurred: ';
  static const String isInternet = 'Internet connection is available';
  static const String isNotInternet = 'Internet connection is not available!';
  static const String useADarkTheme = 'Use a dark theme';
  static const String fontSize = 'Font size';
  static const String contactUs = 'Contact us';
  static const String contactUsLink =
      'https://www.instagram.com/_burbon__/?hl=ru';
  static const String logoPath = 'assets/icons8-donut-60.png';
  static const String googleIconPath = 'assets/icons8-google-100.png';
  static const String clearCart = 'Clear cart';
  static const String hello = 'Hello!';
  static const String pleaseLogin = 'Please Login to Your Account';
  static const String emailAddress = 'Email Address';
  static const String password = 'Password';
  static const String name = 'Name';
  static const String invalidEmailFormat = 'Invalid Email format';
  static const String invalidPassword = 'Invalid password';
  static const String invalidNameFormat = 'Invalid Name format';
  static const String noAccount = 'No account? ';
  static const String signUp = 'Sign Up';
  static const String signOut = 'Sign Out';
  static const String pleaseSignUpInApp = 'Please Sign Up in our application';
  static const String alreadyHaveAnAccount = 'Already have an Account?';
  static const String helperTextForPassword = 'At least 6 characters';
}
